language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install pystache"
script:
  - ./get_sterminator.sh
  - ./buildsite.sh

after_success:
  - >
    test $TRAVIS_PULL_REQUEST == "false"
    && test $TRAVIS_BRANCH == "master"
    && bash ./deploy-gh-pages.sh
