name: Build and deploy site
on: [pull_request, push, workflow_dispatch]
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pip deps
        run: pip install pystache
      - name: Install sterminator
        run: ./get_sterminator.sh
      - name: Build site
        run: ./buildsite.sh
      - name: Deploy site
        if: github.ref == 'refs/heads/master'
        env:
          access_key: ${{ secrets.WEBSITE_DEPLOY_KEY }}
        run: ./deploy-gh-pages.sh
